# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.10-slim

# Install dependencies
WORKDIR /app
COPY pyproject.toml .
COPY main.py .
COPY tools ./tools

RUN pip install --no-cache-dir .

# Ensure unbuffered stdout/stderr for MCP protocol
ENV PYTHONUNBUFFERED=1

# Default entrypoint (overridden by Smithery startCommand)
ENTRYPOINT ["python", "main.py"]
